next-page-tester/next-page-tester

- README.md
- package-lock.json
- package.json
- src/__tests__/__fixtures__/pages/api/index.js
- src/__tests__/__fixtures__/pages/blog/99.js
- src/__tests__/__fixtures__/pages/blog/[id].js
- src/__tests__/__fixtures__/pages/blog/index.js
- src/__tests__/__fixtures__/pages/catch-all/[id]/[...slug]/index.js
- src/__tests__/__fixtures__/pages/index.js
- src/__tests__/__fixtures__/pages/optional-catch-all/[id]/[[...slug]]/index.js
- src/__tests__/__fixtures__/pages/ssg/[id].js
- src/__tests__/__fixtures__/pages/ssr/[id].js
- src/__tests__/__fixtures__/pages/with-router/[id].js
- src/__tests__/getPage.test.js
- src/fetchData.js
- src/getPage.js
- src/getPagePaths.js
- src/preparePage.js
- src/utils.js
Feature
Next `useRoute` not supported
Provide returned page with Next router's router provider supplying a mocked router
Improve mocks customisation.
> Wrap returned element with next router context provider

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
- src/commonTypes.ts
- src/preparePage.ts
- src/utils.ts
Minor improvements
- Exclude routerMock props from code coverage
- Fasten `makeDefaultRouterMock` types
- Replace query-string with node's querystring
- Switch from url to URL
> Typescript refinements

- README.md
- src/__tests__/__fixtures__/pages/_app.js
- src/__tests__/__fixtures__/pages/_document.js
- src/__tests__/__fixtures__/pages/custom-app/[id].js
- src/__tests__/__fixtures__/pages/invalid-extension.foo
- src/__tests__/__fixtures__/pages/typescript.ts
- src/__tests__/getPage.test.js
- src/__tests__/pagePathToRegex.test.js
- src/commonTypes.ts
- src/fetchData.ts
- src/getPage.ts
- src/getPagePaths.ts
- src/pagePathToRouteRegex.ts
- src/preparePage.ts
Feature
Custom App component not implemented
- Add `customApp` option to render custom App component.
- Filter out custom App and Document from routing results
- Pre filter out pages with non-allowed file extensions
No
> Optionally wrap page with app component

- README.md
- src/__tests__/__fixtures__/pages/gip/[id].js
- src/__tests__/__fixtures__/pages/multiple-data-fetching.js
- src/__tests__/page-data-fetching.test.js
- src/commonTypes.ts
- src/fetchData.ts
- src/getPageObject.ts
- src/makeRouterObject.ts
Feature
[`getInitialProps`](https://nextjs.org/docs/api-reference/data-fetching/getInitialProps) data fetching method not supported
Extend data fetching to support `getInitialProps`.
Yes.
- [] Docs have been added / updated
> Support pages' getInitialProps

- README.md
- src/__tests__/custom-app/__fixtures__/special-extension/next.config.js
- src/__tests__/custom-app/custom-app.test.tsx
- src/commonTypes.ts
- src/getPage.ts
- src/utils.ts
Feature
Next.js `pageExtensions` config option has to be explicitly declared as `getPage` option.
Retrieve `pageExtensions` option from `next.config.js` + defaults using Next.js internals.
Yes. `pageExtensions` option is removed. A change in `next.config.js/pageExtensions` option is reflected in `next-page-tester` runtime.
> Auto-detect pageExtensions option

- src/__tests__/__fixtures__/pages/ssr/not-found.js
- src/__tests__/__fixtures__/pages/ssr/redirect.js
- src/__tests__/page-data-fetching-special-returns.test.tsx
- src/commonTypes.ts
- src/fetchData/fetchPageData.ts
Breaking change
Currently no return type check is performed against pages' fetching method result. Since Next.js v10 introduced `notFound` and `redirect` return types, we need a way to tell normal `prop` returns from the others.
Throw error when fetching methods return object with missing props field. Object returned by fetching method is made available in `error.payload`.
Yes. Users should handle throws error in case fetching method returns object with missing `props` field.
https://nextjs.org/blog/next-10#redirect-and-notfound-support-for-getstaticprops--getserversideprops
> Support new fetching method result types

- README.md
- src/__tests__/pagePathToRegex.test.ts
- src/__tests__/routing-static-routes.test.tsx
- src/commonTypes.ts
- src/getPageObject.ts
- src/pagePathToRouteRegex.ts
- src/utils.ts
Bug fix
1. #22 
2. routes with trailing slash like `blog/5/` return "not found error"
1. `/` and `/index` route to `pages/index/` as expected.
2. routes with trailing slash like `blog/5/` redirect to their counterpart without slash (`blog/5`)
Further routes with trailing slash
Yes, if the tests involved the routes types covered by this PR.
> Fix default routing behaviour with trailing slash

- README.md
- package-lock.json
- package.json
- src/__tests__/page-data-fetching.test.tsx
- src/commonTypes.ts
- src/fetchData/makeContextObject.ts
- src/getPageObject.ts
- src/utils.ts
Feature
Supports Next v.9.
- Drop support for Next v.9
- Support Next v.10
- Add `resolvedUrl` to `/getServerSideProps` context
Yes. Users should update their project to consume Next v.10
> Next 10 support

- README.md
- src/__tests__/client-navigation.test.tsx
- src/__tests__/custom-app/custom-app.test.tsx
- src/__tests__/page-data-fetching.test.tsx
- src/__tests__/pages-discovery/pages-discovery.test.js
- src/__tests__/router-mocking.test.tsx
- src/__tests__/routing-dynamic-routes.test.tsx
- src/__tests__/routing-static-routes.test.tsx
- src/getPage.tsx
Feature
`getPage` returns the page element, preventing method from returning additional info.
`getPage` returns an object with a `page` field holding the page element. The returning object will possibly be extended with additional info.
Yes:
```js
const myPage = getPage({ route: '/my-route' });
```
...becomes
```js
const { page: myPage } = getPage({ route: '/my-route' });
```
> Return an object with page property

- README.md
- src/__tests__/custom-app/custom-app.test.tsx
- src/getPage.tsx
Options default change
`useCustomApp` option defaults to `false`
`useCustomApp` option defaults to `true`
Yes. Users should explicitly opt-out from custom app detection and rendering.
> Default useCustomApp option to true

- .github/workflows/ci.yml
CI optimization
`npm run pepare` executed twice in CI pipeline.
CI fires consecutively `npm run ci` and `npm run pepare`. But `npm run ci` calls automatically `npm run pepare` after dependencies are installed
Call just `npm run ci`. 
No
> ci: don't explicitly trigger prepare script

- README.md
Add some documentation for cookies.
Note: this PR is targeting `support-mocking-cookies` and not `master`.
> docs: cookies

- src/__tests__/client-navigation/client-navigation.test.tsx
Test fix.
'client-navigation' tests log warning during execution (triggering console.warn is part of the test itself, not a side effect).
Temporarily mock `console.warn` to avoid error log.
No.
> test: prevent console.warn from logging error

- src/RouterProvider.tsx
- src/__tests__/client-navigation/client-navigation.test.tsx
Improvement
Warning is logged on un-awaited client side navigation, but it lacks some additional information to make it easier to debug which transition the warning relates to (its hard to pinpoint the problem when jest is executing tests in parallel and logging all over the place)
Previous and next route are included in the log
No
> chore: log un-awaited navigation routes

- @types/stealthy-require/index.d.ts
- README.md
- package-lock.json
- package.json
- patches/jest-runtime+26.6.3.patch
- src/RouterProvider.tsx
- src/__tests__/global-object/__fixtures__/pages/gip.js
- src/__tests__/global-object/__fixtures__/pages/ssr.js
- src/__tests__/global-object/global-object.test.tsx
- src/_app/fetchAppData.ts
- src/_app/getCustomAppFile.ts
- src/_app/render.tsx
- src/_document/render.tsx
- src/commonTypes.ts
- src/fetchData/fetchPageData.ts
- src/getPageObject.ts
- src/loadPage.ts
- src/server.ts
- src/testHelpers.ts
- src/utils.ts
- tsconfig.json
This PR tries to extend current `server` idea to workaround #67 and #64. The main issue here consists of being able to access the same module in both "browser" and "non-browser" environment. This approach tries to consider "browser" mode modules as default and keep a "non-browser" copy of the relevant modules in a `server` instance initialized when `getPage` gets called.
Relevant modules are:
- pages
- custom app/document
- some Next.js modules (like `next/dist/next-server/lib/side-effect`)
...
> feature: require pages in browser and non-browser environment

- package.json
Bug fix
`patch-package` command is fired when packages is installed by final user. (Should be a dev-only command, instead)
Trigger `patch-package` on `prepare` (which fires only at dev install)
No.
> fix: patch Jest on prepare (dev-only)

- src/__tests__/use-app/__fixtures__/custom-app-with-gip/pages/page.js
- src/__tests__/use-app/__fixtures__/special-extension/pages/_app.tsx
- src/__tests__/use-app/use-app.test.tsx
- src/_app/fetchAppData.ts
Bug fix
Pages receive `pageProps` from custom app even when `useApp` is set to `false`
Ensure `useApp = false` prevents custom app from fetching data whatsoever
No
> fix: prevent app from executing data fetching when useApp is false

- @types/stealthy-require/index.d.ts
- src/__tests__/__utils__/_document.ts
- src/__tests__/global-object/__fixtures__/pages/_document.js
- src/__tests__/global-object/document-global-object.test.tsx
- src/__tests__/use-document/use-document.test.tsx
- src/_document/DefaultDocument.tsx
- src/_document/Main.tsx
- src/_document/fetchDocumentData.ts
- src/_document/render.tsx
- src/testHelpers.ts
- src/utils.ts
Render custom `_document` in server context.
`client` version of `_document`  is used.
No
> feat: render document in server context

- src/__tests__/cookies/__fixtures__/ssr/pages/authenticated.tsx
- src/__tests__/cookies/__fixtures__/ssr/pages/login.tsx
- src/__tests__/cookies/cookies.test.tsx
- src/fetchData/fetchPageData.ts
- src/fetchData/makeContextObject.ts
- src/fetchData/makeHttpObjects.ts
- src/server.ts
Bug fix -- add parsed `cookies` property to `GetServerSidePropsContext`. This is available from Next `10.0.4` and was added in this PR: https://github.com/vercel/next.js/pull/19724
`req.cookies` are empty in `GetServerSidePropsContext`
No
> fix: add req.cookies property in "getServerSideProps"

- src/__tests__/__utils__/expectDOMElementsToMatch.ts
- src/__tests__/__utils__/index.ts
- src/__tests__/new-returns/__fixtures__/pages/page.tsx
- src/__tests__/new-returns/new-returns.test.tsx
- src/getPage.tsx
- src/makeRenderMethods.ts
Feature
Expose `renderHtml` and `render` methods:
```js
const { renderHTML, render } = await getPage({
```
- `renderHTML ` replaces current DOM with the SSR DOM
- `render` calls `renderHTML ` and hydrate `App` component to `__next` root element
No.
`render` is currently hydrating using `@testing-library/react`. We might consider replacing it with plain `react-dom/server`'s hydrate().
> [next] feature: expose render and renderHTML methods

- pages/page.js
- src/__tests__/__utils__/PropsPrinter.tsx
- src/__tests__/__utils__/expectDOMElementsToMatch.ts
- src/__tests__/__utils__/index.ts
- src/__tests__/__utils__/makeNextRootElement.ts
- src/__tests__/__utils__/renderWithinNextRoot.ts
- src/__tests__/client-navigation/client-navigation.test.tsx
- src/__tests__/cookies/cookies.test.tsx
- src/__tests__/dynamic-import/dynamic-import.test.tsx
- src/__tests__/global-object/__fixtures__/pages/_document.js
- src/__tests__/global-object/__fixtures__/pages/gip.js
- src/__tests__/global-object/__fixtures__/pages/page.tsx
- src/__tests__/global-object/__fixtures__/pages/ssr.js
- src/__tests__/global-object/app-global-object.test.tsx
- src/__tests__/global-object/page-global-object.test.tsx
- src/__tests__/page-data-fetching/page-data-fetching.test.tsx
- src/__tests__/page-extensions/page-extensions.test.tsx
- src/__tests__/pages-discovery/in-root/pages/page.js
- src/__tests__/pages-discovery/in-src/src/pages/page.js
- src/__tests__/pages-discovery/pages-discovery.test.tsx
- src/__tests__/referer/referer.test.tsx
- src/__tests__/router-mocking/router-mocking.test.tsx
- src/__tests__/routing/routing-dynamic-routes.test.tsx
- src/__tests__/routing/routing-static-routes.test.tsx
- src/__tests__/ssr-redirect/ssr-redirect.test.tsx
- src/__tests__/third-party/aws-amplify/aws-amplify.test.ts
- src/__tests__/use-app/use-app.test.tsx
- src/makeRenderMethods.ts
Test update
Current tests retrieve `page` element from `getPage` return object and render it with `@testinbn-library/react`
Since we're considering switching to a new render strategy based on pre-render SSR html in JSDOM and then mount `page` element into it with a `hydrate` call (using `render` or `renderHTML` methods), tests should be rewritten to adhere to the new testing flow.
No, but it's part of a wider breaking change.
The migration is still ongoing...
> [next] test migration

- package-lock.json
- src/__tests__/real-world-example/real-world-example.test.tsx
- src/__tests__/use-document/use-document.test.tsx
- src/makeRenderMethods.ts
Feature
JSDOM root `html` element is not updated with `html` attributes returned from SSR render (this should happen in `renderHTML`)
Parse the `html` string with an XML parsee, retrieve `html` elements attribute and manually append them to JSDOM `html` element.
Using an XML parser to get these few attributes seems overkill, but I haven't been able to find a better way to update JSDOM `html` root element attributes.
@Meemaw if a simpler solution came to your mind, I'm all ears. I feel like there has to be a better way, but...
> [next] Render root html element attributes

- README.md
- src/__tests__/get-page-return/get-page-return.test.tsx
- src/__tests__/global-object/app-global-object.test.tsx
- src/__tests__/global-object/document-global-object.test.tsx
- src/__tests__/global-object/page-global-object.test.tsx
- src/__tests__/pages-discovery/pages-discovery.test.tsx
- src/__tests__/ssr-redirect/ssr-redirect.test.tsx
- src/__tests__/use-document/use-document.test.tsx
- src/getPage.tsx
- src/makeRenderMethods.ts
Refactor
Rename `getPage` return values.
Current API:
```js
const { render, renderHTML, html, page } = await getPage({ options });
```
New API:
```js
const { render, serverRender, serverRenderToString, page } = await getPage({ options });
```
Yes.
> [next] Rename return object

- src/RouterProvider.tsx
- src/__tests__/client-navigation/client-navigation.test.tsx
- src/__tests__/no-default-export/no-default-export.test.ts
- src/__tests__/options-errors-handling.test.ts
- src/__tests__/page-data-fetching/page-data-fetching-special-returns.test.tsx
- src/__tests__/page-data-fetching/page-data-fetching.test.tsx
- src/__tests__/page-extensions/page-extensions.test.tsx
- src/__tests__/pages-discovery/pages-discovery.test.tsx
- src/__tests__/routing/routing-dynamic-routes.test.tsx
- src/__tests__/routing/routing-static-routes.test.tsx
- src/__tests__/use-app/use-app.test.tsx
- src/fetchData/fetchPageData.ts
- src/getPage.tsx
- src/getPageObject.ts
- src/loadPage.ts
- src/utils.ts
Refactor 
Error messages throw non uniform error messages
Error messages comply with following template: `[next-page-tester] Error message`
No
> refactor: uniform error messages

- README.md
- src/__tests__/next-config/__fixtures__/next.config.js
- src/__tests__/next-config/__fixtures__/pages/page.tsx
- src/__tests__/next-config/next-config.test.tsx
- src/getPage.tsx
- src/nextConfig.ts
- src/server.ts
- src/setNextRuntimeConfig.ts
- src/utils.ts
Feature
`next/config` is not set and always returns `undefined`.
Support [Next.js runtime configuration](https://nextjs.org/docs/api-reference/next.config.js/runtime-configuration) and set different `next/config` values based on `server` or `client` env. 
Yes.
> feature: support next/config runtime configuration

- src/RouterProvider.tsx
- src/__tests__/client-navigation/__fixtures__/PageA.tsx
- src/__tests__/client-navigation/__fixtures__/pages/a.tsx
- src/__tests__/client-navigation/__fixtures__/pages/gip/a.js
- src/__tests__/client-navigation/__fixtures__/pages/ssr/a.js
- src/__tests__/client-navigation/client-navigation.test.tsx
Fixes https://github.com/toomuchdesign/next-page-tester/issues/121
Client side navigation with `UrlObject` does not work
Client side navigation with `UrlObject` works
No
> fix: client side object navigation

- src/__tests__/ssr-redirect/ssr-redirect.test.tsx
- src/constants.ts
- src/makePageElement.ts
- src/utils.ts
Fix: throw error on external route redirect
404 page is rendered when external redirect happens.
Error is thrown when external redirect happens.
> fix: throw error on external route redirect

- README.md
- src/__tests__/setup.ts
- src/__tests__/test-helpers/__fixtures__/pages/index.tsx
- src/__tests__/test-helpers/test-helpers.test.ts
- src/index.ts
- src/pure.ts
- src/testHelpers.ts
- Improves DX by setting up auto cleanup & test initialisation
User has to manually call `initTestHelpers` in their testing setup to avoid errors at runtime.
Users don't have to do anything. They can directly use `next-page-tester` imports and everything will work out of the box.
No
> Auto init test helpers

- README.md
- src/__tests__/non-isolated-modules/__fixtures__/api.ts
- src/__tests__/non-isolated-modules/__fixtures__/pages/page.tsx
- src/__tests__/non-isolated-modules/non-isolated-modules.test.ts
- src/commonTypes.ts
- src/getNextFiles.ts
- src/getPage.tsx
- src/testHelpers.ts
- src/utils.ts
Re-introduce `nonIsolatedModules` option. This enables module mocking in "server" context.
It is not possible to mock a module (e.g. SDK) in "server" context. Because test is executed in "client" context any mocks configured in test code are not applied to "server" context.
Add ability to mark such modules as "nonIsolated". Identity of those modules is then preserved in both contexts and mocking is possible.
No
> fix: revive nonIsolatedModules

- src/__tests__/environment-variables/__fixtures__/env-vars/pages/page.tsx
- src/__tests__/environment-variables/environment-variables.test.tsx
- src/setEnvVars.ts
Pass through `NODE_ENV` to the client
`NODE_ENV` is not available in `client` context which is:
- not in-line with `Next.JS`
- makes it hard to have conditional logic based on `process.env.NODE_ENV === 'test'`
`NODE_ENV` is passed through to the client context
No
> fix(env): pass-through NODE_ENV to client

- README.md
- package-lock.json
- package.json
- src/nextConfig.ts
- src/router/makeRouterMock.ts
Chore
Update Next dev and peer version to `^10.0.8` and update router mock to include new typed props
Yes.
> chore: bump next version to v10.0.8

- src/__tests__/i18n/__fixtures__/next.config.js
- src/__tests__/i18n/__fixtures__/pages/another.tsx
- src/__tests__/i18n/__fixtures__/pages/index.tsx
- src/__tests__/i18n/i18n.test.ts
- src/router/RouterProvider.tsx
- src/router/makeRouterMock.ts
- src/utils.ts
Populate `i18n` (locale) field in the router.
Fixes https://github.com/toomuchdesign/next-page-tester/issues/188
`i18n` field are not populated.
`i18n` field are populated.
No
> feat: implement routing locales

- src/nextConfig.ts
- src/page/getPageFile.ts
Bug fix
#200
Patch `config-utils` only if require succeeds.
No
> fix: don't throw if config-utils doesn't exist

- README.md
- src/__tests__/wrapper/__fixtures__/App/pages/_app.tsx
- src/__tests__/wrapper/__fixtures__/App/pages/a.tsx
- src/__tests__/wrapper/wrapper.test.tsx
- src/_app/render.tsx
- src/commonTypes.ts
Closes #210
Adds a `wrapper.App` option, similar to the existing `wrapper.Page`.
Only a `Page` wrapper is available, which is certainly useful, but insufficient for certain behaviors.
#210
No
> feat: Add custom wrapper for _app

- src/__tests__/i18n/__fixtures__/pages/ssg.js
- src/__tests__/i18n/__fixtures__/pages/ssr.js
- src/__tests__/i18n/i18n.test.ts
- src/fetchData/fetchPageData.ts
- src/fetchData/makeContextObject.ts
Increased fidelity to Next.js behaviors during page data fetching, adding the missing locale properties to the context object passed to `getServerSideProps()` and `getStaticProps()`.
An incomplete context object is passed, lacking the locale-related properties.
The properties `locale`, `locales`, and `defaultLocale` are now available on SSR/SSG context objects, matching the behavior of Next.js.
No
> feat: Add locale fields to data fetching contexts

- src/utils.ts
This fixes the following error, i.e. #216, which should still be open:
```
the module factory of `jest.mock()` is not allowed to reference any out-of-scope variables.     Invalid variable access: moduleName
```
This fixes #216 for me using TypeScript using @latest for all libraries (i.e. next-11.0.2) in a TypeScript environment.
There would seem to be something "lost in translation" between the `.ts -> .js with types.d.ts` conversion for the npm package.
This solution comes from a monkey-patch, but it's a simple refactor of one variable name on 4 lines, so it should be good to go.
Bug fix for breaking bug on current npm package version `next-page-tester@0.27.0` installed with `npm install --save-dev next-page-tester --force`.
Same as closed #216. Given the complexity of this project, it's …
> fix: change moduleName -> mockModuleName

- package-lock.json
- src/page/getPageFile.ts
Bug fix
Ts type check because of [TS v4.4 `strictCatchClauseTypes` option](https://github.com/microsoft/TypeScript/issues/36775)
Strict type cought error objects.
No
> fix: strict type catch error

- README.md
- package-lock.json
- package.json
- src/_document/fetchDocumentData.ts
- src/_document/render.tsx
- src/testHelpers.ts
Bug fix
Jest can't handle mixed CommonJs/ES Modules imports in Next.js
Set global [`process.env.__NEXT_TEST_MODE`](https://github.com/vercel/next.js/blob/v12.1.0/packages/next/server/config.ts#L639) variable which Next.js uses to not mix imports
Yes, Next.js version supported `>= 12.1.0`
Should replace #294 #295
> Next v12 compatibility (2nd attempt)
