CHANGELOG.md
README.md

v0.4.0 docs update

---

README.md
src/__tests__/custom-app/custom-app.test.tsx
src/commonTypes.ts
src/getPage.ts
src/preparePage.ts

Option renaming
Rename `customApp` option -> `useCustomApp`
Yes.

Rename customApp option -> useCustomApp

---

CHANGELOG.md

Update docs for v0.5.0

---

CHANGELOG.md
README.md

Update docs for v0.6.0

---

CHANGELOG.md

Update docs for v0.7.0

---

CHANGELOG.md

v0.8.0 docs update

---

.github/workflows/ci.yml
package-lock.json
package.json
src/getPagePaths.ts
src/loadPage.ts
src/utils.ts

- Fixes https://github.com/toomuchdesign/next-page-tester/issues/31
- Adds CI (using Github Actions) to run on different platforms (ubuntu, windows, OSx) to prevent future regressions
No

fix: os insensitive path handling

---

.github/workflows/ci.yml
.travis.yml
package-lock.json
package.json

CI Update
CI running both on Travis and GH workflows
Move whole CI to GH workflows
No

Migrate Travis CI to GH workflows

---

.github/workflows/ci.yml

CI update
Replace Codecov with coveralls
No

Replace codecov with coveralls

---

src/_app/DefaultApp.tsx
src/_app/fetchAppData.ts
src/_app/getCustomAppFile.ts
src/_app/index.ts
src/_app/render.tsx
src/_document/fetchDocumentData.ts
src/_document/render.tsx
src/commonTypes.ts
src/fetchData/index.ts
src/makePageElement.ts
src/makePageElement.tsx

Refactoring
Organise custom app code the same way as custom document's
No

Uniform app and document code

---

CHANGELOG.md
README.md

v0.9.0 docs update

---

package-lock.json
package.json
src/__tests__/real-world-example/__fixtures__/package.json
src/__tests__/real-world-example/__fixtures__/pages/page-a.tsx
src/__tests__/real-world-example/real-world-example.test.tsx
src/getPageObject.ts
src/loadPage.ts

Bug fix
Using libraries that rely on `window` object, e.g. `react-hook-form` (https://github.com/react-hook-form/react-hook-form/blob/398bb117b6dac0e9d4c5bc2d7c2ed328c932332e/src/useForm.ts#L77) won't work
Using libraries that rely on `window` object works.
No

fix: client side window

---

.all-contributorsrc
CHANGELOG.md
README.md

v0.10.0 docs update

---

CHANGELOG.md
package-lock.json
package.json

v0.10.1 docs update

---

README.md
src/_document/render.tsx
src/getPage.tsx
src/makePageElement.ts

Refactor
Refactor `makePage` so that we can release before #57 gets merged.
No

Redirect refactoring

---

CHANGELOG.md

v0.11.0 docs update

---

CHANGELOG.md

v0.12.0 docs update

---

CHANGELOG.md
README.md

v0.14.0 docs update

---

README.md

Docs update
If you find the time you're welcome to add anything you think we should mention @Meemaw.

[next] Update docs

---

CHANGELOG.md

v0.15.0 docs update

---

README.md
examples/01-testing-seo.md
examples/02-enzyme.md

Docs update
Add an `example` folder to store a few significant testing case enabled by next page tester.
No

[next] Add examples folder

---

CHANGELOG.md

v0.16.0 docs update 

---

package-lock.json
package.json
renovate.json

Fixes https://github.com/toomuchdesign/next-page-tester/issues/111
`cookie` dependency is missing
...

fix: add cookie dependency

---

CHANGELOG.md

v0.16.2 docs update

---

CHANGELOG.md

v0.17.0 docs update

---

src/server.ts

Refactor
`executeAsIfOnServer` and `executeAsIfOnServerAsync` duplicate most of their implementation.
Extract common logic to as separate function.
No.

refactor: remove duplications in server utils

---

CHANGELOG.md
README.md

v0.19.0 docs update

---

src/commonTypes.ts
src/getNextFiles.ts

chore: remove duplication by leveraging generics

---

CHANGELOG.md

v0.20.0 docs update

---

README.md

Docs update
Add a note about handling special imports. See: #155 

docs: add a note about handling special imports

---

jest/dist.config.js

fix: jest dist moduleNameMapper configuration

---

src/commonTypes.ts
src/getPageObject/getRouteInfo.ts
src/getPageObject/makeRouteInfo.ts

Refactor
Minor routing refatoring
No

refactor: cleanup routing

---

.all-contributorsrc
CHANGELOG.md
README.md

Docs update
#153 
Change routes resolution implementation and rely on `getSortedRoutes` from Next.js
No.

v0.21.1 docs update 

---

README.md

docs: sort dev env notes

---

CHANGELOG.md

docs: v0.22.0 update

---

README.md

Docs update
Improve jest patching instructions
Provide more viable alternatives as network requests mocking solutions

docs: rephrase some paragraphs

---

README.md

docs: add a note about missing mocked network requests

---

.github/ISSUE_TEMPLATE/bug.md

Docs update
Explicitly ask about patching Jest and highlight the need of a reproducible example.

docs: update bug issue template

---

src/getPage.tsx
src/nextConfig.ts

fixes https://github.com/toomuchdesign/next-page-tester/issues/185
...

fix: await `loadConfig`

---

.all-contributorsrc
CHANGELOG.md
README.md

docs: v0.23.0 update

---

CHANGELOG.md

docs(CHANGELOG): populate "i18n" (locale) router fields

---

.all-contributorsrc
CHANGELOG.md
README.md

docs: v0.24.1 update 

---

CHANGELOG.md

docs: v0.24.2 update

---

examples/04-snapshots.md

Added example for snapshot tests
Nope.
#207

chore: added snapshot example

---

src/404/makeNotFoundPageObject.ts
src/commonTypes.ts
src/fetchData/fetchPageData.ts
src/fetchData/makeContextObject.ts
src/getPageObject/getRouteInfo.ts
src/getPageObject/makeRouteInfo.ts
src/router/makeRouterMock.ts
src/utils.ts

Refactor
Extract getLocales util
No

refactor: extract getLocales util

---

CHANGELOG.md

docs: v0.25.0 update

---

CHANGELOG.md

docs: v0.26.0 update

---

src/__tests__/use-app/__fixtures__/custom-app-with-gip-custom-props/pages/_app.js
src/__tests__/use-app/__fixtures__/custom-app-with-gip-custom-props/pages/gip.js
src/__tests__/use-app/__fixtures__/custom-app-with-gip-custom-props/pages/ssg.js
src/__tests__/use-app/__fixtures__/custom-app-with-gip-custom-props/pages/ssr.js
src/__tests__/use-app/use-app.test.tsx
src/_app/render.tsx
src/_document/render.tsx
src/commonTypes.ts
src/fetchData/fetchPageData.ts
src/getPage.tsx
src/page/makePageElement.ts

fixes toomuchdesign/next-page-tester#220
custom props in custom _app GIP are passed to App component on all kind of pages (GIP, SSR, SSG)
No
- ~~Docs have been added / updated~~

fix custom app props not being passed to App

---

.all-contributorsrc
CHANGELOG.md
README.md

docs: v0.26.1 update 

---

README.md
package-lock.json
package.json

chore: update Next to v11

---

.all-contributorsrc
CHANGELOG.md
README.md

docs: update changelog

---

CHANGELOG.md

docs: update docs for v0.31
